### ISSUE TITLE
Configuration Option to disable logging

### ISSUE THREAD

**Issue by jgoldhammer** [jirutka/spring-rest-exception-handler#16]
Hi,

I am using your module (thanks for providing it!) and I would like to skip logging because I have my own LoggingFilter which takes care of logging and has a more complex logic to decide what to log and in which case.

In my eyes, it would make sense to provide an option to disable logging for your module.
What do you think?

Thanks,
Jens

**Comment by jirutka** [comment]
This module uses slf4j logging facade, you can simply disable logging for particular classes of this module in your logging implementation (e.g. logback, log4j, …). For example in logback:

```xml
<logger name="cz.jirutka.spring.exhandler.handlers.RestExceptionHandler" level="OFF" />
```

**Comment by jgoldhammer** [comment]
ok, thanks...
