### ISSUE TITLE
Customized error code not working

### ISSUE THREAD

**Issue by t2349** [jirutka/spring-rest-exception-handler#17]
Hi, 
I created an exception class and the handler class for this exception, assign an status code 461 to it, the code is not a standard http code, also I copied your errorMessages.properties file and added the following:

```
org.test.exception.MyURLParamException.title=Wrong Query URL Parameter
org.test.exception.MyURLParamException.detail=The parameter you have sent is probably malformed. 
```

The exception class looks like:

```java
public class MyURLParamException extends Exception {
	  private int code;

	  public MyURLParamException(String message) {
	    super(message != null ? message : "MyURLParamException was thrown");
	    this.code = 461;
	  }

	  public int getCode() {
	    return this.code;
	  }
}
```

I configured the bean as this:

```xml
<bean id="httpErrorMessageSource"
	      class="org.springframework.context.support.ReloadableResourceBundleMessageSource">
	        <property name="basenames" value="classpath:/WEB-INF/errorMessages.properties"/>
    		<property name="defaultEncoding" value="UTF-8"/>
    </bean>

```

then I run the web app to test the error handling, I got 

java.lang.IllegalArgumentException: No matching constant for [461]
        at org.springframework.http.HttpStatus.valueOf(HttpStatus.java:488)
        at org.test.exception.MyURLParamExceptionHandler.handleException(MyURLParamExceptionHandler.java:15)
        at org.test.exception.MyURLParamExceptionHandler.handleException(MyURLParamExceptionHandler.java:11)
        at cz.jirutka.spring.exhandler.RestHandlerExceptionResolver.handleException(RestHandlerExceptionResolver.java:140)
        at cz.jirutka.spring.exhandler.RestHandlerExceptionResolver.doResolveException(RestHandlerExceptionResolver.java:118)

But if I changed status code from 461 to 400, it will work.

Anything I did is not correct?

Thanks
Dave

**Comment by jirutka** [comment]
How does class ` org.test.exception.MyURLParamExceptionHandler` look like?

**Comment by t2349** [comment]
Thanks for your response, this is the handler class:

public class MyURLParamExceptionHandler  implements RestExceptionHandler<MyURLParamException, ErrorMessage> {
	
	  @Override
	  public ResponseEntity<ErrorMessage> handleException(MyURLParamException exception, HttpServletRequest request) {
	    HttpStatus status = HttpStatus.valueOf(exception.getCode());
	    ErrorMessage errorMessage = new ErrorMessage();
	    errorMessage.setTitle("MyURLParamException");
	    errorMessage.setStatus(status);
	    errorMessage.setDetail(exception.getMessage());

	    return new ResponseEntity<>(errorMessage, status);
	  }
	}

**Comment by jirutka** [comment]
I hope that you already see where’s the problem…

**Comment by t2349** [comment]
Oh, HttpStatus.valueOf(461) will throw exception since 461 is not a http status code.

**Comment by jirutka** [comment]
Exactly. It’s a bug in your own code. `ErrorMessage.setStatus()` accepts both `HttpStatus` and `Integer`.

**Comment by t2349** [comment]
OK, thanks, I changed to this, it works, another problem is it is not using my configuration in my errorMessages.properties file, which I have the values as following:
org.noblis.exception.CWxMapURLParamException.type=461
org.noblis.exception.CWxMapURLParamException.title=Wrong Query URL Parameter
org.noblis.exception.CWxMapURLParamException.detail=The parameter you have sent is probably malformed.

So how do I get these values used with your framework?

	  @Override
	  public ResponseEntity<ErrorMessage> handleException(MyURLParamException exception, HttpServletRequest request) {
	    //HttpStatus status = HttpStatus.valueOf(exception.getCode());
	    ErrorMessage errorMessage = new ErrorMessage();
	    errorMessage.setTitle("MyURLParamException");
	    errorMessage.setStatus(exception.getCode());
	    errorMessage.setDetail(exception.getMessage());

	    return new ResponseEntity<>(errorMessage, HttpStatus.BAD_REQUEST);
	  }

**Comment by t2349** [comment]
I guess your framework is not automatically doing that, so I need to load the errorMessages.properties resource file and explicitly read the pairs and set them in the handler class, is that right?

Thanks

**Comment by jirutka** [comment]
No, you’re not. Please read carefully the readme, it’s all here. Note missing `.properties` in the basename.

**Comment by t2349** [comment]
I followed the readme, you advised to use this:
<bean id="httpErrorMessageSource"
      class="org.springframework.context.support.ReloadableResourceBundleMessageSource"
      p:basename="classpath:/WEB-INF/errorMessages"
      p:defaultEncoding="UTF-8" />
but I got p is not defined error, so I changed to:
<bean id="httpErrorMessageSource"
	      class="org.springframework.context.support.ReloadableResourceBundleMessageSource">
	        <property name="basenames" value="classpath:/WEB-INF/errorMessages"/>
    		<property name="defaultEncoding" value="UTF-8"/>
    </bean>

But I still got the same result, the configured values are not used in the error messages:

org.noblis.exception.CWxMapURLParamException.type=461
org.noblis.exception.CWxMapURLParamException.title=Wrong Query URL Parameter
org.noblis.exception.CWxMapURLParamException.detail=The parameter you have sent is probably malformed.

The error messages look like this:

<problem>
<detail>
URL parameters are not specified correctly: is
</detail>
<status>461</status>
<title>MyURLParamException</title>
</problem>

**Comment by jirutka** [comment]
There’s `basename`, not `basenames` in the readme.

The `p:` is called [p-namespace](http://docs.spring.io/autorepo/docs/spring/current/spring-framework-reference/html/beans.html#beans-p-namespace).

**Comment by t2349** [comment]
I changed to this:
<bean id="httpErrorMessageSource"
	      class="org.springframework.context.support.ReloadableResourceBundleMessageSource" 
	      p:basename="classpath:/WEB-INF/errorMessages"
          p:defaultEncoding="UTF-8">

And added this:
xmlns:p="http://www.springframework.org/schema/p"

Retested, it is still the same, any clues?

Thanks

**Comment by t2349** [comment]
I mean the whole bean looks like this:

<bean id="httpErrorMessageSource"
	      class="org.springframework.context.support.ReloadableResourceBundleMessageSource" 
	      p:basename="classpath:/WEB-INF/errorMessages"
          p:defaultEncoding="UTF-8">
      
    </bean>

**Comment by t2349** [comment]
I mean the whole bean looks like this:
<bean id="httpErrorMessageSource"
	      class="org.springframework.context.support.ReloadableResourceBundleMessageSource" 
	      p:basename="classpath:/WEB-INF/errorMessages"
          p:defaultEncoding="UTF-8">
     
    </bean>

**Comment by jirutka** [comment]
Hmm, I’ve missed this before, `classpath:/WEB-INF/errorMessages` is almost certainly wrong, `/WEB-INF` is not on the classpath. It’s odd that Spring didn’t throw an exception that it can’t find the file…

Also please learn the basic of [Markdown formatting on GitHub](https://guides.github.com/features/mastering-markdown/), I don’t enjoy fixing every comment of yours…

**Comment by t2349** [comment]
Sorry, you mean class path problem and file is not loaded in at runtime. got it.

Thanks

**Comment by jirutka** [comment]
I don’t use WEB-INF at all these days, but if I recall it correctly, you can use just `/WEB-INF/errorMessages` (without `classpath:` prefix). However my advice is to put this file on the classpath, e.g. `src/main/resources` if you use Maven structure.

**Comment by t2349** [comment]
I put under classes as this: 
p:basename="classpath:/WEB-INF/classes/errorMessages"
I can see it is in the undeployed folder in tomcat.
but the result is still the same, must be something else.

**Comment by jirutka** [comment]
This doesn’t make damn sense. If you use standard project structure, then move `errorMessages.properties` into the directory `src/main/resources/org/test/exception` and set `basename="classpath:org/test/exception/errorMessages"`. Alternatively, if you have somehow messed project structure, then put it directly to the same directory as `MyURLParamExceptionHandler.java`.

**Comment by t2349** [comment]
Hi, sorry to bother, I downloaded the source code and added a lot debug messages, and rebuild a jar and deployed to my local repository, then I changed my pom file to point to that jar, retested with my app, I found out the ErrorMessageRestExceptionHandler has never got called, there is a getMessage() method, which is supposed to get message from the messageSource, anything I did wrong? the following is some of the debug messages I added:

./catalina.out:DDDD RestHandlerExceptionResolver constructor returnTypeMethodParam: org.springframework.core.MethodParameter@850e6f61
./catalina.out:DDDD RestHandlerExceptionResolver build contentNegotiationManager: null
./catalina.out:DDDD RestHandlerExceptionResolver build defaultContentType: application/json
./catalina.out:DDDD RestHandlerExceptionResolver build resolver: cz.jirutka.spring.exhandler.RestHandlerExceptionResolver@59233c53
./catalina.out:DDDD RestHandlerExceptionResolver build withDefaultMessageSource: true
./catalina.out:DDDD RestHandlerExceptionResolver build messageSource: org.springframework.context.support.ReloadableResourceBundleMessageSource: basenames=[classpath:/org/noblis/exception/errorMessages]
./catalina.out:DDDD RestHandlerExceptionResolver build messageSource: org.springframework.context.support.ReloadableResourceBundleMessageSource: basenames=[classpath:/org/noblis/exception/errorMessages]
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.ErrorMessageRestExceptionHandler@5d6649b5
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.ErrorMessageRestExceptionHandler@453a9c2b
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.ErrorMessageRestExceptionHandler@78aa8f9a
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.HttpMediaTypeNotSupportedExceptionHandler@38abe578
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.HttpRequestMethodNotSupportedExceptionHandler@576f3839
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.ErrorMessageRestExceptionHandler@46a52d3b
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.ErrorMessageRestExceptionHandler@6a5fac2a
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.ErrorMessageRestExceptionHandler@d38043c
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.ErrorMessageRestExceptionHandler@23b84b52
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.MethodArgumentNotValidExceptionHandler@4c1b66eb
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.ErrorMessageRestExceptionHandler@5bb2bdbe
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.NoSuchRequestHandlingMethodExceptionHandler@16e64b10
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.ErrorMessageRestExceptionHandler@77657045
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.ErrorMessageRestExceptionHandler@605e6c7c
./catalina.out:DDDD RestHandlerExceptionResolver build handler: org.noblis.exception.RSQLExceptionHandler@117876fd
./catalina.out:DDDD RestHandlerExceptionResolver build handler: cz.jirutka.spring.exhandler.handlers.ErrorMessageRestExceptionHandler@2ecf7284
./catalina.out:DDDD RestHandlerExceptionResolver build handler: org.noblis.exception.MyURLParamExceptionHandler@2caaf2
./catalina.out:DDDD RestHandlerExceptionResolver constructor returnTypeMethodParam: org.springframework.core.MethodParameter@850e6f61
./catalina.out:DDDD RestHandlerExceptionResolver build contentNegotiationManager: null
./catalina.out:DDDD RestHandlerExceptionResolver build defaultContentType: application/json
./catalina.out:DDDD RestHandlerExceptionResolver build resolver: cz.jirutka.spring.exhandler.RestHandlerExceptionResolver@a551286
./catalina.out:DDDD RestHandlerExceptionResolver resolveExceptionHandler clazz: org.noblis.exception.MyURLParamException
./catalina.out:DDDD RestHandlerExceptionResolver handleException: org.noblis.exception.MyURLParamException
./catalina.out:DDDD RestHandlerExceptionResolver processResponse entity: <400 Bad Request,ErrorMessage(type=null, title=MyURLParamException, status=461, instance=null),{}>

Thanks

**Comment by t2349** [comment]
Finally I got it. I just need to write  my handler class to extend from ErrorMessageRestExceptionHandler, since this class loads error messages from the resource file.
Thanks for your help.

**Comment by jirutka** [comment]
Aha, I’ve forgotten your original objective meanwhile. If you wanna fill the `ErrorMessage` from the properties file, then why you even defines your own handler? Moreover, you’re just setting the `ErrorMessage` properties based on the given exception, so it’s totally unnecessary. The main benefit of this library is support for simple mapping of exceptions without writing exception handlers.

You can do this instead:

```xml
<bean id="restExceptionResolver"
      class="cz.jirutka.spring.exhandler.RestHandlerExceptionResolverFactoryBean">
    <property name="messageSource" ref="httpErrorMessageSource" />
    <property name="defaultContentType" value="application/xml" />
    <property name="exceptionHandlers">
        <map>
            <entry key="org.noblis.exception.CWxMapURLParamException" value="461" />
        </map>
    </property>
</bean>
```

```properties
org.noblis.exception.CWxMapURLParamException.type=461
org.noblis.exception.CWxMapURLParamException.title=MyURLParamException
org.noblis.exception.CWxMapURLParamException.detail=URL parameters are not specified correctly: #{ex.message}
```
