### ISSUE TITLE
Question about how to apply this framework to filter

### ISSUE THREAD

**Issue by t2349** [jirutka/spring-rest-exception-handler#18]
Hi team, sorry for my confusion, this is just a question, not an issue, since I can not find a place to ask.
I applied the framework for controllers, it works very well, my question is how to apply the framework to filters, since filter is called before controller, and my filter already throws AuthenticationException, how to let the framework handle this exception?

Thanks
Dave

**Comment by jirutka** [comment]
This is not related to this library, but Spring itself. Sadly I don’t know how filters interacts with Spring’s exception handlers and if it’s possible to intercept even exceptions thrown from filters. I assume that you’ve already tried it and it doesn’t catch them?

**Comment by t2349** [comment]
Yes, I tried, it does not catch them, I will look into it.
Thanks

**Comment by t2349** [comment]
Another question, I saw you have this JSON format:
{
    "type": "http://example.org/errors/validation-failed",
    "title": "Validation Failed",
    "status": 422,
    "detail": "The content you've send contains 2 validation errors.",
    "errors": [{
        "field": "title",
        "message": "must not be empty"
    }, {
        "field": "quantity",
        "rejected": -5,
        "message": "must be greater than zero"
    }]
}

Mine is like this:
{"type":"461","title":"Bad URL Parameter","status":400,"detail":"The URL parameter you have sent is probably malformed."}

How do I fill all the fields for "errors"? since mine has errors filled up.

Thanks
Dave

**Comment by jirutka** [comment]
This is generated for `javax.validation.ConstraintViolationException` (Java Bean Validation, implemented e.g. by Hibernate Validator) by [cz.jirutka.spring.exhandler.handlers.ConstraintViolationExceptionHandler](https://github.com/jirutka/spring-rest-exception-handler/blob/master/src/main/java/cz/jirutka/spring/exhandler/handlers/ConstraintViolationExceptionHandler.java).

**Comment by t2349** [comment]
Got it.
Thanks
