### ISSUE TITLE
Use of LocaleContextHolder vs. request.getLocale()

### ISSUE THREAD

**Issue by amr** [jirutka/spring-rest-exception-handler#8]
Hi,

In `ErrorMessageRestExceptionHandler#resolveMessage`, the active locale is determined using `HttpServletRequest#getLocale`. In Spring land, I believe `LocaleContextHolder` is the canonical way of retrieving the locale in the current context.

**Comment by jirutka** [comment]
Hi, you're right, thanks for the suggestion! I'll fix it tomorrow.
